name: "[MacroEtapa: Infraestrutura]"
description: "Backlog [Macroetapa: Infra-Setup]"
title: "[Infraestrutura] - Definição de comandos Makefile, criação artefatos Docker"
labels:
  - tipo:macroetapa
  - area:infra
  - prioridade:alta
assignees:
  - leafarRafael-Dev
  
body:
  - type: markdown
    attributes:
      value: |
        Necessidades macro para criação da infraestrutura basica do projeto.

  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      description: Qual o objetivo principal desta tarefa?
      placeholder: Ex Configurar arquivos essenciais para orquestração com Docker.
    validations:
      required: true

  - type: textarea
    id: makefile
    attributes:
      label: Makefile - Comandos esperados
      description: Liste os comandos que deverão estar presentes no Makefile.
      placeholder: Ex build, install, run, stop, clean
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Marque os itens conforme forem sendo implementados
      options:
        - label: Makefile criado com comandos básicos

