name: "Template para definição de macro etapa"
description: "Utilizar este template para definição de backlog macro do projeto"
title: "[Definição de Macro etapa]"
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Preencha os campos abaixo para detalhar a tarefa de criação da base da infraestrutura.

  - type: input
    id: objetivo
    attributes:
      label: Objetivo
      description: Qual o objetivo principal desta tarefa?
      placeholder: Ex Configurar arquivos essenciais para orquestração com Docker.
    validations:
      required: true

  - type: textarea
    id: makefile
    attributes:
      label: Makefile - Comandos esperados
      description: Liste os comandos que deverão estar presentes no Makefile.
      placeholder: Ex build, install, run, stop, clean
    validations:
      required: true

  - type: textarea
    id: dockerfiles
    attributes:
      label: Dockerfiles a serem criados
      description: Quais serviços precisarão de Dockerfile?
      placeholder: Ex nginx, postgresql, aspnet, angular
    validations:
      required: true

  - type: textarea
    id: compose
    attributes:
      label: docker-compose - Requisitos
      description: O que o docker-compose precisa gerenciar? (redes, volumes, serviços...)
      placeholder: Ex Gerenciar as imagens criadas, volumes compartilhados, redes entre os containers
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Marque os itens conforme forem sendo implementados
      options:
        - label: Makefile criado com comandos básicos
        - label: Dockerfiles criados para todos os serviços
        - label: docker-compose.yml funcional com redes e volumes
        - label: Testes de build realizados com sucesso
